package routers

import (
	"api-360proxy/auth/controllers"
	"api-360proxy/web/controller"
	"api-360proxy/web/middleware"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "api-360proxy/web/docs" // docs is generated by Swag CLI, you have to import it.
)

func InitRouter() *gin.Engine {
	r := gin.New()
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	r.Use(middleware.CORSMiddleware())
	// r.Delims("[[", "]]")
	// r.LoadHTMLGlob("views/*")
	//r.LoadHTMLGlob("views/**/*")
	//r.HTMLRender = templateRender.LoadTemplates("./views")
	// 加载404错误页面
	//r.NoRoute(func(c *gin.Context) {
	//	//c.HTML(http.StatusOK, "404.html", gin.H{})
	//	r.GET("404", controller.Index404)
	//})
	//加载静态资源，例如网页的css、js
	r.Static("/static", "./static")
	r.Static("/upload", "./upload")
	r.GET("/", controller.Index)
	r.GET("qrcode", controller.Qrcode)
	r.GET("/web/connect", controllers.Connect) //接口联通测试
	//if setting.RunMode == "debug" {
	//	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	//}
	systemApi := r.Group("/api/", middleware.AreaMiddleware())
	{
		systemApi.GET("f5", controller.FreshCache)
	}

	systemApi.GET("userMemberUpdate", controller.FreshUserMemberLevel)
	//官网接口
	webRouter(r)
	// 个人中心相关
	centerRouter(r)
	//代理管理器
	proxyManageRouter(r)

	// swagger文档访问
	r.GET("/MzYwc3dhZ2dlcg/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return r
}
