package routers

import (
	"api-360proxy/auth/controllers"
	"api-360proxy/web/controller"
	"api-360proxy/web/middleware"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "api-360proxy/web/docs" // docs is generated by Swag CLI, you have to import it.
)

func InitRouter() *gin.Engine {
	r := gin.New()
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	r.Use(middleware.CORSMiddleware())
	//加载静态资源，例如网页的css、js
	r.Static("/static", "./static")
	r.Static("/upload", "./upload")
	r.GET("/", controller.Index)
	r.GET("qrcode", controller.Qrcode)
	r.GET("/web/connect", controllers.Connect) //接口联通测试
	systemApi := r.Group("/api/", middleware.AreaMiddleware())
	{
		systemApi.GET("f5", controller.FreshCache)
	}

	systemApi.GET("userMemberUpdate", controller.FreshUserMemberLevel)

	r.GET("/notify/onfido", controller.IdVerifyNotify)        //认证通知接口
	r.POST("/notify/onfido", controller.IdVerifyNotify)       //认证通知接口
	r.GET("/notify/tencent_kyc", controller.TencentKycNotify) //认证通知接口
	//官网接口
	webRouter(r)
	// 个人中心相关
	centerRouter(r)
	//代理管理器
	proxyManageRouter(r)
	// swagger文档访问
	r.GET("/MzYwc3dhZ2dlcg/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return r
}
